function loadData(){
data = {
    fullName: {
        f: 'forest',
        d: 'desert',
        m: 'mountain',
        u: 'unknown',
    },
    shortName: {
        forest: 'f',
        desert: 'd',
        mountain: 'm',
        unknown: 'u',
    },
    temples: {
        desert: {wall: 'ss',contents: [['e',7],['st',7],['c',4],['ii',2],['gi',1],['sb',1]]},
        mountain: {wall: 'mcs',contents: [['e',13],['px',1],['c',5],['gi',1],['ii',2],['lpx',1]]},
        forest: {wall: 'mcs',contents: [['e',9],['st',7],['s',5],['gi',1],['ii',2],['fb',1]]},
    },
    biomeProb: {
        forest: [['g',90],['tf',4.5],['r',4.5],['psp',1/3],['sfp',1/3],['mrp',1/3]],
        desert: [['ds',199],['db',1]],
    },
    maxClicks: {
        r: { def: 100, px: 50, ipx: 25 },
        tf: { def: 200, x: 100, ix: 50 },
        io: { def: 300, px: 150, ipx: 75 },
        co: { def: 200, px: 100, ipx: 50 },
        go: {def: 500, ipx: 100},
        ch: { def: 100, x: 50, ix: 25 },
        f: { def: 200, px: 100, ipx: 50 },
        nv: { def: 200, px: 100, ipx: 50 },
        db: { def: 50, x: 25, ix: 12 },
        lp: { def: 50, x: 25, ix: 12 },
        ss: { def: 100, px: 50, ipx: 25},
        psp: { def: 25},
        mrp: { def: 25},
        sfp: { def: 25},
        mcs: { def: 100, px: 50, ipx: 25 },        
    },
    ms: {
        x: 1, px: 1, bx: 1, sw: 1, ix: 1, ipx: 1, ibx: 1, isw: 1, ih: 1, ic: 1, il: 1, ib: 1, sb: 1, lpx: 1, fb: 1, ms: 1,
    },
    food: {
        ms: 8,
        mr: 3,
    },
    dmg: {
        def: 2,
        px: 4,
        sw: 6,
        x: 5,
        bx: 7,
        ipx: 7,
        isw: 9,
        ix: 8,
        ibx: 10,
        fb: 10,
        lpx: 5,
    },
    recipes: [
        [['p', 4], [['l', 1]], 'none'],
        [['st', 4], [['p', 2]], 'none'],
        [['sw', 1], [['s', 5], ['st', 10]], 'none'],
        [['px', 1], [['s', 5], ['st', 10]], 'none'],
        [['x', 1], [['s', 5], ['st', 10]], 'none'],
        [['bx', 1], [['s', 10], ['st', 10]], 'none'],
        [['ii', 1], [['c', 1], ['io', 1]], 'f'],
        [['ch', 1], [['p', 20]], 'none'],
        [['cs', 1], [['s', 3]], 'none'],
        [['t', 1], [['st', 1], ['gl', 1]], 'none'],
        [['f', 1], [['cs', 10], ['t', 10]], 'none'],
        [['nv', 1], [['ii', 5]], 'none'],
        [['isw', 1], [['ii', 5], ['st', 10]], 'nv'],
        [['ipx', 1], [['ii', 5], ['st', 10]], 'nv'],
        [['ix', 1], [['ii', 5], ['st', 10]], 'nv'],
        [['ibx', 1], [['ii', 10], ['st', 10]], 'nv'],
        [['ih', 1], [['ii', 5]], 'nv'],
        [['ic', 1], [['ii', 15]], 'nv'],
        [['il', 1], [['ii', 10]], 'nv'],
        [['ib', 1], [['ii', 5]], 'nv'],
        [['gi',1],[['go',1],['c',1]], 'f'],
        [['bwl',1],[['p',3]], 'none'],
        [['ms',1],[['bwl',1],['mr',1],['ps',1],['sf',1],['gl',1]], 'none'],
    ],  
    dropitem: {
        r: { def: ['s', [1, 1]] },
        tf: { def: ['l', [4, 7]] },
        lp: { def: ['l', [1, 1]] },
        fb: { def: ['fb', [1, 1]] },
        io: { def: ['', [0, 0]], px: ['io', [1, 1]], ipx: ['io', [1, 1]], lpx: ['ii', [1, 1] ] },
        co: { def: ['', [0, 0]], px: ['c', [1, 1]], ipx: ['c', [1, 1]], lpx: ['c', [1, 1]] },
        f: { def: ['f', [1, 1]] },
        nv: { def: ['nv', [1, 1]] },
        ch: { def: ['ch', [1, 1]] },
        db: { def: ['st', [1, 3]] },
        ss: {def: ['ss', [1, 1]]},
        mrp: {def: ['mr',[1,1]]},
        sfp: {def: ['sf',[1,1]]},
        psp: {def: ['ps',[1,1]]},
        go: {def: ['',[0,0]], ipx: ['go', [1, 1]], lpx: ['gi', [1, 1] ]},
        mcs: {def: ['mcs',[1,1]]},
    },
    defaultTile: {
        forest: 'g',
        mountain: 'sr',
        desert: 'ds',
    },
    placable: [
        ['f', 'f'],
        ['ch', 'ch'],
        ['nv', 'nv'],
        ['l', 'lp'],
        ['ss','ss'],
        ['mcs','mcs'],
    ],
    walkable: ['g', 'sr', 'ds', 'io', 'co', 'db','psp','mrp','sfp','go'],
    blockimg: {
        g: [0, 0],
        cs: [1, 0],
        f: [2, 0],
        t: [3, 0],
        fb: [4, 0],
        tf: [0, 1],
        r: [1, 1],
        sw: [2, 1],
        l: [3, 1],
        s: [4, 1],
        p: [0, 2],
        st: [1, 2],
        px: [2, 2],
        x: [3, 2],
        bx: [4, 2],
        lp: [0, 3],
        lpx: [1, 3],
        ds: [2, 3],
        sr: [3, 3],
        io: [4, 3],
        co: [0, 4],
        c: [1, 4],
        ii: [2, 4],
        ch: [3, 4],
        db: [4, 4],
        isw: [0, 5],
        ipx: [1, 5],
        ix: [2, 5],
        ibx: [3, 5],
        nv: [4, 5],
        blank: [0, 6],
        gl: [1, 6],
        ih: [2, 6],
        ic: [3, 6],
        il: [4, 6],
        ib: [0, 7],
        sb: [1, 7],
        dc: [2, 7],
        ss: [3, 7],
        mrp: [4, 7],
        mr: [0, 8],
        psp: [1, 8],
        ps: [2, 8],
        sfp: [3, 8],
        sf: [4, 8],
        mc: [0,9],
        go: [1,9],
        gi: [2,9],
        mcs: [3,9],
        fc: [4,9],
        blank2: [0,10],
        bwl: [1,10],
        ms: [2,10],
    },
    armor: {
        h: ['ih','e'],
        c: ['ic','e'],
        l: ['il','e'],
        b: ['ib','e','sb'],
    },
    armordef: {
        ih: 1,
        ic: 3,
        il: 2,
        ib: 1,
        sb: 0,
        e: 0,
    },
    armordraw: {
        ih: { l: 24, r: 25, sl: 26, sr: 27, al: 28, ar: 29 },
        ib: { l: 18, r: 19, sl: 20, sr: 21, al: 22, ar: 23 },
        il: { l: 12, r: 13, sl: 14, sr: 15, al: 16, ar: 17 },
        ic: { l: 6, r: 7, sl: 8, sr: 9, al: 10, ar: 11 },
        sb: { l: 0, r: 1, sl: 2, sr: 3, al: 4, ar: 5 },
    }, 
    spawnpatch: {
        io: [200, [5, 12]],
        co: [300, [5, 20]],
        go: [50, [3, 8]],
    },
    mobs: {
        blob: {
            get: {
                l: 0,
                r: 1,
                dl: 2,
                dr: 3,
            },
            dmg: 2,
            type: 'hostile',
            spawn: 'forest',
            speed: 0.02,
            health: 10,
            drop: [['gl', [0, 2]]],
            framerate: 5,
            cycleLoop: [0, 1, 2, 3, 4, 5, 6, 7, 8],
        },
        g: {
            get: {
                l: 4,
                r: 5,
                dl: 6,
                dr: 7,
            },
            dmg: 5,
            type: 'hostile',
            speed: 0.02,
            health: 25,
            drop: [],
            framerate: 5,
            cycleLoop: [0, 1, 2, 3, 4, 5, 6, 7, 8],
        }
    },
    viewdata: {
        cs: 'Cobblestone',
        f: 'Furnace*Placable*Smelts iron',
        t: 'Torch',
        sw: 'Sword*+4 damage',
        l: 'Log*Placable',
        s: 'Rock',
        p: 'Planks',
        st: 'Stick',
        px: 'Pickaxe*Breaks rocks faster*Mines coal/iron*+2 damage',
        x: 'Axe*Cuts trees faster*+3 damage',
        bx: 'Battleaxe*+5 damage',
        io: 'Iron ore',
        c: 'Coal',
        ii: 'Iron ingot',
        ch: 'Chest*Placable*Stores items',
        isw: 'Iron sword*+7 damage',
        ipx: 'Iron pickaxe*Mines even faster*Can mine gold*+5 damage',
        ix: 'Iron axe*Cuts trees even faster*+6 damage',
        ibx: 'Iron battleaxe*+8 damage',
        nv: 'Anvil*Placable*Crafts iron tools',
        gl: 'Gel',
        ih: 'Iron helmet*Armor*+1 defense',
        ic: 'Iron chestplate*Armor*+3 defense',
        il: 'Iron leggings*Armor*+2 defense',
        ib: 'Iron boots*Armor*+1 defense',
        sb: 'Sandrunner boots*2x speed in desert',
        lpx: 'Lava pickaxe*Mines incredibly slowly*Smelts iron automatically*+3 damage',
        fb: 'Forest blade*+8 damage',
        tf: 'Tree',
        g: 'Grass',
        r: 'Rock',
        sr: 'Stone',
        co: 'Coal ore',
        ds: 'Sand',
        db: 'Dead bush',
        lp: 'Log',
        ss: 'Sandstone*Placable',
        dc: 'Crown of the desert*Summons the Sandcrawler',
        sf: 'Sunflower',
        sfp: 'Sunflower',
        mr: 'Mushroom',
        mrp: 'Mushroom',
        psp: 'Pansy',
        ps: 'Pansy',
        mc: 'Crown of the mountains*Summons the Stonecrusher',
        go: 'Gold ore',
        gi: 'Gold ingot*Currency',
        mcs: 'Mossy cobblestone',
        fc: 'Crown of the forest*Summons the Treestalker',
        bwl: 'Bowl',
        ms: 'Mushroom stew*Food*Heals 8 health',
    },
    partial: ['nv','ch'],
    setPos: ['g']
};
}