var data = {
    maxClicks: {
        r: { def: 250, px: 100, ipx: 50},
        t4: { def: 250, x: 100, ix: 50},
        io: { def: 500, px: 250, ipx: 125},
        co: { def: 375, px: 200, ipx: 100},
        ch: { def: 125, x: 50, ix: 25},
        f: { def: 250, px: 125, ipx: 75 },
        nvp: { def: 250, px: 125, ipx: 75 },
        db: { def: 50, x: 25, ix: 12 },
        lp: { def: 50, x: 25, ix: 12}
    },
    dmg: {
        def: 2,
        px: 4,
        sw: 6,
        x: 5,
        bx: 7,
        ipx: 7,
        isw: 9,
        ix: 8,
        ibx: 10,
    },
    recipes: [
        [['p', 4], [['l', 1]], 'none'],
        [['st', 4], [['p', 2]], 'none'],
        [['sw', 1], [['s', 5], ['st', 10]], 'none'],
        [['px', 1], [['s', 5], ['st', 10]], 'none'],
        [['x', 1], [['s', 5], ['st', 10]], 'none'],
        [['bx', 1], [['s', 10], ['st', 10]], 'none'],
        [['ii', 1], [['c', 1], ['io', 1]], 'f'],
        [['ch', 1], [['p', 20]], 'none'],
        [['cs', 1], [['s', 3]], 'none'],
        [['t', 1], [['st', 1], ['gl', 1]], 'none'],
        [['f', 1], [['cs', 10], ['t', 10]], 'none'],
        [['nv', 1], [['ii', 5]], 'none'],
        [['isw', 1], [['ii', 5], ['st', 10]], 'nvp'],
        [['ipx', 1], [['ii', 5], ['st', 10]], 'nvp'],
        [['ix', 1], [['ii', 5], ['st', 10]], 'nvp'],
        [['ibx', 1], [['ii', 10], ['st', 10]], 'nvp'],
        [['cbf', 1], [['bf', 1], ['c', 1]], 'f'],
    ],
    dropitem: {
        r: { def: ['s', [1, 2]] },
        t4: { def: ['l', [4, 7]] },
        lp: { def: ['l', [1, 1]] },
        fb: { def: ['fb', [1, 1]] },
        io: { def: ['', [0, 0]], px: ['io', [1, 1]], ipx: ['io', [1, 1]] },
        co: { def: ['', [0, 0]], px: ['c', [1, 1]], ipx: ['c', [1, 1]] },
        f: { def: ['f', [1, 1]] },
        nvp: { def: ['nv', [1, 1]] },
        ch: { def: ['ch', [1, 1]] },
        db: { def: ['st', [1, 3]] },
        lp: { def: ['l', [1, 1]] },
    },
    defaultTile: {
        forest: 'g',
        mountain: 'sr',
        desert: 'ds',
    },
    placable: [
        ['f', 'f'],
        ['ch', 'ch'],
        ['nv', 'nvp'],
        ['l', 'lp'],
    ],
    walkable: ['g', 'sr', 'ds', 'io', 'co', 'db'],
    blockimg: {
        g: [0, 0],
        cs: [1, 0],
        f: [2, 0],
        t: [3, 0],
        exp: [4, 0],
        t4: [0, 1],
        r: [1, 1],
        sw: [2, 1],
        l: [3, 1],
        s: [4, 1],
        p: [0, 2],
        st: [1, 2],
        px: [2, 2],
        x: [3, 2],
        bx: [4, 2],
        lp: [0, 3],
        fb: [1, 3],
        ds: [2, 3],
        sr: [3, 3],
        io: [4, 3],
        co: [0, 4],
        c: [1, 4],
        ii: [2, 4],
        ch: [3, 4],
        db: [4, 4],
        isw: [0, 5],
        ipx: [1, 5],
        ix: [2, 5],
        ibx: [3, 5],
        nv: [4, 5],
        nvp: [0, 6],
        gl: [1, 6],
    },
    spawnpatch: {
        io: [200, [5, 12]],
        co: [300, [5, 20]],
    },
    mobs: {
        blob: {
            get: {
                l: 0,
                r: 1,
                dl: 2,
                dr: 3,
            },
            type: 'hostile',
            spawn: 'forest',
            speed: 0.02,
            health: 10,
            drop: [['gl', [0, 2]]],
            framerate: 5,
            cycleLoop: [0, 1, 2, 3, 4, 5, 6, 7, 8],
        }
    }
};